defaults: &defaults
  working_directory: ~/project/frontend
  executor:
    name: node/default


version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  test:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      - run:
          name: install python
          command: sudo apt update && sudo apt install python-minimal
      - node/install-packages:
          pkg-manager: yarn
          app-dir: ~/project/frontend
          cache-path: ~/project/frontend/node_modules
      - run: yarn test
  lint-and-typecheck:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      - run:
          name: install python
          command: sudo apt update && sudo apt install python-minimal
      - node/install-packages:
          pkg-manager: yarn
          app-dir: ~/project/frontend
          cache-path: ~/project/frontend/node_modules
      - run: yarn lint
      - run: yarn typecheck

workflows:
  build-and-test:
    jobs:
      - test
      - lint-and-typecheck