defaults: &defaults
  working_directory: ~/frontend
  executor:
    name: node/default


version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
  lint:
    <<: *defaults
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn lint

workflows:
  build-and-test:
    jobs:
      - test
      - lint